import Head from 'next/head';
import Link from 'next/link';
import { Routes } from './routes';
import { AppBar, Button, Container, Typography } from '@material-ui/core';
import { useAuth } from '../utils/sweet-state/authStore';

import { supabase } from '../utils/initSupabase';
export default function Home() {
	const [state, actions] = useAuth();

	const fakeLogin = async () => {
		const { user, session, error } = await supabase.auth.signIn({
			email: 'foo@bar.com',
			password: 'tester',
		});
		if (error) {
			setErr({ msg: error.message, error: true });
		} else {
			const { data, error } = await supabase.from('users').select().filter('user_id', 'eq', user.id);
			if (error) {
				setErr({ error: true, msg: 'Something went wrong. Please try again.' });
			} else {
				actions.login(user, session, data[0]);
			}
		}
	};
	return (
		<>
			<Head>
				<title>Car Projecto</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<AppBar
				position='sticky'
				style={{ display: 'flex', justifyContent: 'space-between', flexDirection: 'row', padding: 10, alignItems: 'center' }}
			>
				<Button onClick={e => console.log(state)}>State</Button>
				<Button onClick={fakeLogin}>Instant Login</Button>
				<Typography variant='h5'>Car Projecto</Typography>
				<div>
					{!state.user ? (
						<>
							<Link href='/auth/signUp'>
								<Button color='inherit'>Sign Up</Button>
							</Link>
							<Link href='/auth/login'>
								<Button color='inherit'>Login</Button>
							</Link>
						</>
					) : (
						<div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
							<Typography>Welcome, {state.data.username}</Typography>

							<Link href={`/profile/${state.data.username}`}>
								<Button color='inherit'>Profile</Button>
							</Link>
						</div>
					)}
				</div>
			</AppBar>
			<Routes />
		</>
	);
}
