import Head from 'next/head';
import Link from 'next/link';
import { Routes } from './routes';
import { AppBar, Button, Typography } from '@material-ui/core';
import { useAuth } from '../utils/sweet-state/authStore';
export default function Home() {
	const [state] = useAuth();
	return (
		<>
			<Head>
				<title>Car Projecto</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<AppBar
				position='sticky'
				style={{ display: 'flex', justifyContent: 'space-between', flexDirection: 'row', padding: 10, alignItems: 'center' }}
			>
				<Button onClick={e => console.log(state)}>State</Button>
				<Typography variant='h5'>Car Projecto</Typography>
				<div>
					{!state.user ? (
						<>
							<Link href='/auth/signUp'>
								<Button color='inherit'>Sign Up</Button>
							</Link>
							<Link href='/auth/login'>
								<Button color='inherit'>Login</Button>
							</Link>
						</>
					) : (
						<>
							<Link href='/profile'>
								<Button color='inherit'>Profile</Button>
							</Link>
						</>
					)}
				</div>
			</AppBar>
			<Routes />
		</>
	);
}
